version: "3.8"

services:
  frontend:
    build: ./App
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "80:80" # Frontend accessible at http://localhost:3000
    environment:
      - REACT_APP_API_URL="http://backend:8000"
    restart: always

  backend:
    build: ./backend
    container_name: fastapi-backend
    depends_on:
      - mongodb
    expose:
      - "7000" # Exposing backend port internally to Nginx
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx-backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount the custom nginx.conf file
    ports:
      - "8000:80" # Nginx should listen on port 80 on the host and proxy traffic to the backend
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
